function domain = Domain(xmin, xmax, T)
    L = abs(xmin-xmax);
    domain = struct("xmin", xmin, ...
        "xmax", xmax, ...
        "T", T, ...
        "L", abs(xmin-xmax), ...
        "delta", min(-1*xmin, xmax) / L);
end